### PR TITLE
Rearrange manifest to be test-path centric

### LINKED ISSUE #1208: When manifest is enabled, navigating from a file view to a directory view is very slow
To reproduce:

1. Make sure manifest is enabled in https://staging.wpt.fyi/flags
2. Go to https://staging.wpt.fyi/results/css/css-flexbox
3. Navigate into any file
4. Navigate back

There's no network request between 3 & 4 as the directory view is already in memory, but the navigation is still extremely slow. Profiling shows JS is busy doing `computeTestType`.

### PR DESCRIPTION
**Pull request by lukebjerring**
## Description
Otherwise, it's computationally expensive to find a test path (we have to iterate the whole manifest and look up the `manifest.items[type][file][0]` entry).

Fixes #1208

### CODE REVIEW

**Comment by lukebjerring** [comment]
Still too slow async; let's rearrange the manifest instead.

**Comment by Hexcles** [comment]
@lukebjerring is this ready for review?

**Comment by lukebjerring** [comment]
Yep

File: webapp/components/wpt-results.js [hunk 1]
```diff
@@ -505,15 +504,10 @@ class WPTResults extends WPTColors(WPTFlags(SelfNavigation(LoadingState(TestRuns
       return path;
     }
     // Filter in case any types are fully missing.
```
Comment (Hexcles) [inline webapp/components/wpt-results.js]:
```suggestion
    // Ensure leading slash.
```

File: webapp/components/wpt-results.js [hunk 2]
```diff
@@ -534,12 +528,10 @@ class WPTResults extends WPTColors(WPTFlags(SelfNavigation(LoadingState(TestRuns
...
     }
-    const item = Object.values(manifest.items['reftest']).find(v => v.find(i => i[0] === path));
-    // In item[0], the 2nd item is the refs array, and we take the first ref (0).
-    // Then, the ref's 1st item is the url (0). (2nd is the condition, e.g. "==".)
-    // See https://github.com/web-platform-tests/wpt/blob/master/tools/manifest/item.py#L141
-    const refPath = item && item[0][1][0][0];
-    return this.computeTestURL(testType, refPath);
+    const metadata = manifest.get(path);
+    if (metadata && metadata.refPath) {
+      return this.computeTestW3CURL(testType, metadata.refPath);
```
Comment (Hexcles) [inline webapp/components/wpt-results.js]: I don't see `computeTestW3CURL` anywhere in master or this patch? Where's it defined?

File: webapp/components/wpt-results.js (hunk 1 above)
Comment (Hexcles) [reply webapp/components/wpt-results.js]: In fact, do we still need to do it? Looks like the updated `fetchManifestForSHA` already ensures the leading slash.

File: webapp/components/wpt-results.js [hunk 3]
```diff
@@ -851,14 +857,10 @@ class WPTResults extends WPTColors(WPTFlags(SelfNavigation(LoadingState(TestRuns
     // Add an empty row for all the tests known from the manifest.
     const knownNodes = {};
     if (this.manifest && !this.search) {
-      for (const type of Object.keys(this.manifest.items)) {
+      for (const [path, {type}] of Object.entries(this.manifest)) {
         if (['manual', 'reftest', 'testharness', 'wdspec'].includes(type)) {
```
Comment (Hexcles) [inline webapp/components/wpt-results.js]: Might be worthwhile to keep the `TEST_TYPES` constant and use it here.
