### PR TITLE
Fix Chrome crashes when running WebDriver tests

### LINKED ISSUE #1788: Chrome WebDriver tests failing on master
Retries didn't seem to help. Example: https://travis-ci.com/web-platform-tests/wpt.fyi/jobs/284471146#L3283

```
        	Error:      	Error waiting for test runs: unknown error - 100: chrome not reachable
        	            	  (Session info: chrome=80.0.3987.87)
        	            	  (Driver info: chromedriver=80.0.3987.16 (320f6526c1632ad4f205ebce69b99a062ed78647-refs/branch-heads/3987@{#185}),platform=Linux 5.0.0-1026-gcp x86_64)
```

Meanwhile, PR checks seem fine.

### PR DESCRIPTION
**Pull request by Hexcles**
Fixes #1788

Success example: https://travis-ci.com/web-platform-tests/wpt.fyi/jobs/284672904

Root cause: Chrome 80 does not like to run on an 8-bit X11 server, and Xvfb by default uses a 1280x1024x8 display. By switching to a 24-bit display, the tests pass again. There's an [internal Chromium bug](https://crbug.com/1025266#c16) tracking this (sorry Googler-only).

### CODE REVIEW

File: webdriver/webdriver.go [hunk 1]
```diff
@@ -83,7 +83,8 @@ func runWebdriverTest(t *testing.T, test webdriverTest) {
 func GetWebDriver() (*selenium.Service, selenium.WebDriver, error) {
 	var options []selenium.ServiceOption
 	if *startFrameBuffer {
-		options = append(options, selenium.StartFrameBuffer())
+		options = append(options, selenium.StartFrameBufferWithOptions(
```
Comment (Hexcles) [inline webdriver/webdriver.go]:
```suggestion
		// Use a 24-bit display to avoid https://github.com/web-platform-tests/wpt.fyi/issues/1788.
		options = append(options, selenium.StartFrameBufferWithOptions(
```
