### PR TITLE
[Triage Metadata] Show all metadata in triage mode

### LINKED ISSUE #2300: Show all metadata (in triage mode)
Previously in #2068 we started to hide the bug icon (and the associated metadata) for a subtest in the file view if the subtest is passing to reduce UI clutter.

However, sometimes people would like to see the metadata regardless. One very reasonable scenario is when triaging tests one by one. Showing metadata (bug links) for previously triaged but now passing subtests could provide additional context (subtests that are still failing in the same test are likely related to the previously fixed subtests).

We can consider "triage mode" enabled as a signal for more interests in metadata.

### PR DESCRIPTION
**Pull request by KyleJu**
Fix #2300.

## Test
See [here](https://passing-subtest-icon-dot-wptdashboard-staging.uk.r.appspot.com/results/eventsource/format-field-id-null.window.html?label=experimental&label=master&aligned) and its [wpt-metadata](https://github.com/web-platform-tests/wpt-metadata/blob/master/eventsource/META.yml)

### CODE REVIEW

File: webapp/components/test-file-results-table.js [hunk 1]
```diff
@@ -433,12 +433,13 @@ class TestFileResultsTable extends WPTFlags(Pluralizer(AmendMetadataMixin(WPTCol
...
   }
 
-  shouldDisplayMetadata(index, subtestname, metadataMap, status) {
+  shouldDisplayMetadata(index, subtestname, metadataMap, status, isTriageMode) {
     if (!metadataMap) {
       return false;
     }
 
-    if (!this.hasFailed(status)) {
+    // Show icons for passing subtests when triageMode is enabled.
```
Comment (stephenmcgruer) [inline webapp/components/test-file-results-table.js:441]:
```suggestion
    // Show icons for passing subtests when triageMode is enabled.
    // See https://github.com/web-platform-tests/wpt.fyi/issues/2300
```

**Review by stephenmcgruer — APPROVED** [review]
