### PR TITLE
Do not fail when GID already exists in Docker

### LINKED ISSUE #250: GID XX already exists
```
sworddance@MacBook-Pro wpt.fyr.orig$ ./util/docker-dev/run.sh
[  2018-06-08 14:49:22  INFO  ]  Creating docker instance for dev server. Instance name: wptd-dev-instance
[  2018-06-08 14:49:22  WARN  ]  Found existing docker instance wptd-dev-instance. Remove?
Confirm (y/N): y
[  2018-06-08 14:49:29  INFO  ]  Stopping wptd-dev-instance...
wptd-dev-instance
[  2018-06-08 14:49:30  INFO  ]  wptd-dev-instance stopped.
[  2018-06-08 14:49:30  INFO  ]  Removing wptd-dev-instance...
wptd-dev-instance
[  2018-06-08 14:49:31  INFO  ]  wptd-dev-instance removed.
[  2018-06-08 14:49:31  INFO  ]  Starting docker instance wptd-dev-instance...
8f2faf5b1be5dadb289e1b5fc2df3d35b7012bdd3dd1074825d39042f1d737a5
[  2018-06-08 14:49:31  INFO  ]  Setting up local user
groupadd: GID '20' already exists
```
what is GID XX already exists

### PR DESCRIPTION
**Pull request by Hexcles**
Fixes #250 .

@AutomatedTester no I wasn't able to find a more elegant solution. In fact, this is a common issue with lots of blogs introducing essentially the same workaround we're already using (e.g. https://denibertovic.com/posts/handling-permissions-with-docker-volumes/). This PR is a workaround for an edge case of the workaround...

### CODE REVIEW

File: util/commands.sh [hunk 1]
```diff
@@ -6,9 +6,9 @@ function wptd_chown() {
   docker exec -u 0:0 "${DOCKER_INSTANCE}" chown -R $(id -u $USER):$(id -g $USER) $1
 }
 function wptd_useradd() {
-  docker exec -u 0:0 "${DOCKER_INSTANCE}" groupadd -g "$(id -g $USER)" user
-  docker exec -u 0:0 "${DOCKER_INSTANCE}" useradd -u "$(id -u $USER)" -g "$(id -g $USER)" user
-  docker exec -u 0:0 "${DOCKER_INSTANCE}" usermod -a -G user root
```
Comment (lukebjerring) [inline util/commands.sh]: I see you've dropped root here - how confident are we that this doesn't break some not-used-by-travis rules?

Comment (Hexcles) [reply util/commands.sh]: Quite confident. I'll revert this if anything breaks :)

And I'll make it clear in the commit message.
