### PR TITLE
Fix Docker environment after #2252

### LINKED ISSUE #2259: [Go 1.12] Local build broken due to #2252
Running `./util/docker-dev/dev_data.sh` returns:

2020/11/18 22:40:47 populate_dev_data.go:54: Adding dev data to local emulator...
2020/11/18 22:40:47 populate_dev_data.go:145: Adding local (empty) secrets...
2020/11/18 22:40:47 appengine.go:102: Closing clients
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x98552c]

goroutine 1 [running]:
cloud.google.com/go/datastore.(*Client).PutMulti(0x0, 0xd53dc0, 0xc0000bc010, 0xc000295120, 0x1, 0x1, 0xaeab20, 0xc0003f6520, 0x0, 0x0, ...)
	/home/user/go/pkg/mod/cloud.google.com/go/datastore@v1.3.0/datastore.go:516 +0x17c
cloud.google.com/go/datastore.(*Client).Put(0x0, 0xd53dc0, 0xc0000bc010, 0xc0003b7fc0, 0xace420, 0xc0003bd5a0, 0x0, 0x0, 0x42d271)
	/home/user/go/pkg/mod/cloud.google.com/go/datastore@v1.3.0/datastore.go:490 +0xe8
github.com/web-platform-tests/wpt.fyi/shared.cloudDatastore.Put(0xd53dc0, 0xc0000bc010, 0x0, 0xd4f6c0, 0xc0003b7fc0, 0xace420, 0xc0003bd5a0, 0xc000295208, 0xa69b1c, 0xbdfdc0, ...)
	/home/user/wpt.fyi/shared/datastore_cloud.go:152 +0x14e
main.addSecretToken(0xd5f1e0, 0xc0003f6500, 0xc52a67, 0xc, 0xace420, 0xc0003bd5a0)
	/home/user/wpt.fyi/util/populate_dev_data.go:324 +0xc0
main.main()
	/home/user/wpt.fyi/util/populate_dev_data.go:147 +0x1109
exit status 2
make: *** [dev_data] Error 1
Makefile:236: recipe for target 'dev_data' failed

This is caused by `datastore: missing project/dataset id` in [appengine.go](https://github.com/web-platform-tests/wpt.fyi/blob/master/shared/appengine.go#L49).

### PR DESCRIPTION
**Pull request by Hexcles**
Fixes #2259.

Make sure we start Cloud Datastore emulator in Docker as well, and plumb
the necessary flags (e.g. the port number) around.

Drive-by: fix a flaky WebDriver test. In api/interop.go, we use
`it.Next` to load the next entity into a struct that may not be zero,
in which case Datastore library will not zero it out first and may leave
stale data in the struct (e.g. if a slice field already has N items but
the entity to be loaded only has N-1 items in that field, the last item
will not be removed from the struct). The issue only surfaced after
PR #2252 as the IDs in Datastore emulator are no longer sequential.

### CODE REVIEW

File: util/docker-dev/web_server.sh [hunk 1]
```diff
@@ -48,6 +48,9 @@ wptd_exec_it dev_appserver.py \
    --admin_port=8000 \
    --api_host=$WPTD_CONTAINER_HOST \
    --api_port=9999 \
-   -A=wptdashboard \
+   --support_datastore_emulator=true \
+   --datastore_consistency_policy=consistent \
+   --datastore_emulator_port=8001 \
+   -A=wptdashboard-local \
```
Comment (KyleJu) [inline util/docker-dev/web_server.sh:54]: Unrelated question: what is this `-A` flag for?

**Review by KyleJu — APPROVED** [review]
Thanks for the quick fix!

File: util/docker-dev/web_server.sh (hunk 1 above)
Comment (Hexcles) [reply util/docker-dev/web_server.sh:54]: To specify the project ID
