### PR TITLE
Set all-permissive CORS for all read-only APIs

### LINKED ISSUE #433: Add CORS headers to /api/
Trying to implement https://github.com/foolip/wpt-rotation/issues/2 as a client-side check doesn't work because "No 'Access-Control-Allow-Origin' header is present on the requested resource." when trying to fetch https://wpt.fyi/api/runs?label=experimental.

### PR DESCRIPTION
**Pull request by Hexcles**
This commit adds Access-Control-Allow-Origin: * to the headers of all
read-only APIs. Fixes #433.

### CODE REVIEW

File: webapp/routes_test.go [hunk 1]
```diff
@@ -40,33 +40,53 @@ func TestInteropAnomaliesBound(t *testing.T) {
...
 func TestRunsBoundHSTS(t *testing.T) {
+	assertHandlerIs(t, "/test-runs", "test-runs")
 	assertHSTS(t, "/test-runs")
 }
 
-func TestApiDiffBound(t *testing.T) {
-	assertBound(t, "/api/diff")
+func TestApiDiffBoundCORS(t *testing.T) {
+	assertHandlerIs(t, "/api/diff", "api-diff")
+	assertCORS(t, "/api/diff")
```
Comment (foolip) [inline webapp/routes_test.go]: Are the APIs that mutate that we should similarly `assertNoCORS` for?
